{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/aunishukri/medicalanalyzer/blob/main/medicalanalyzer.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Install necessary packages\n",
        "!pip install transformers datasets scikit-learn matplotlib\n",
        "\n",
        "# Import libraries\n",
        "from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments\n",
        "from sklearn.model_selection import train_test_split\n",
        "from datasets import Dataset\n",
        "import torch\n",
        "import numpy as np\n",
        "from sklearn.metrics import precision_recall_fscore_support,accuracy_score\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "# Data preparation\n",
        "# Extended data preparation with more examples\n",
        "data = [\n",
        "    {\"text\": \"The patient has a high fever (39°C) and chills.\", \"label\": 1, \"medication\": \"Paracetamol\"},\n",
        "    {\"text\": \"The patient feels tired but has no fever.\", \"label\": 0, \"medication\": \"Rest and hydration\"},\n",
        "    {\"text\": \"Fever with sore throat and body aches.\", \"label\": 1, \"medication\": \"Paracetamol\"},\n",
        "    {\"text\": \"Mild headache with no fever.\", \"label\": 0, \"medication\": \"Rest and hydration\"},\n",
        "    {\"text\": \"The patient has a severe headache and a high temperature.\", \"label\": 1, \"medication\": \"Paracetamol\"},\n",
        "    {\"text\": \"The patient complains of fatigue and body aches but no fever.\", \"label\": 0, \"medication\": \"Rest and hydration\"},\n",
        "    {\"text\": \"High fever with shivering and sweating.\", \"label\": 1, \"medication\": \"Paracetamol\"},\n",
        "    {\"text\": \"No fever but the patient has a mild cough and congestion.\", \"label\": 0, \"medication\": \"Rest and hydration\"},\n",
        "    {\"text\": \"The patient experiences chills and a high fever.\", \"label\": 1, \"medication\": \"Paracetamol\"},\n",
        "    {\"text\": \"The patient has a normal temperature but feels very tired.\", \"label\": 0, \"medication\": \"Rest and hydration\"},\n",
        "    {\"text\": \"The patient has a high fever and a sore throat.\", \"label\": 1, \"medication\": \"Paracetamol\"},\n",
        "    {\"text\": \"The patient feels dizzy but has no fever.\", \"label\": 0, \"medication\": \"Rest and hydration\"},\n",
        "    {\"text\": \"The patient has a fever and is sweating heavily.\", \"label\": 1, \"medication\": \"Paracetamol\"},\n",
        "    {\"text\": \"The patient has no fever but complains of a headache.\", \"label\": 0, \"medication\": \"Rest and hydration\"},\n",
        "    {\"text\": \"High fever and severe body aches.\", \"label\": 1, \"medication\": \"Paracetamol\"},\n",
        "    {\"text\": \"The patient has no fever but feels very weak.\", \"label\": 0, \"medication\": \"Rest and hydration\"},\n",
        "    {\"text\": \"The patient has chills and a high fever.\", \"label\": 1, \"medication\": \"Paracetamol\"},\n",
        "    {\"text\": \"The patient feels nauseous but has no fever.\", \"label\": 0, \"medication\": \"Rest and hydration\"},\n",
        "    {\"text\": \"The patient has a high fever and a headache.\", \"label\": 1, \"medication\": \"Paracetamol\"},\n",
        "    {\"text\": \"The patient has no fever but feels exhausted.\", \"label\": 0, \"medication\": \"Rest and hydration\"},\n",
        "    {\"text\": \"The patient has a high fever and is shivering.\", \"label\": 1, \"medication\": \"Paracetamol\"},\n",
        "    {\"text\": \"The patient has no fever but feels unwell.\", \"label\": 0, \"medication\": \"Rest and hydration\"},\n",
        "    {\"text\": \"The patient has a high fever and body aches.\", \"label\": 1, \"medication\": \"Paracetamol\"},\n",
        "    {\"text\": \"The patient has no fever but feels weak.\", \"label\": 0, \"medication\": \"Rest and hydration\"},\n",
        "    # Class 1 - Fever\n",
        "    {\"text\": \"The patient reports a fever and chills with body aches.\", \"label\": 1, \"medication\": \"Paracetamol\"},\n",
        "    {\"text\": \"High fever along with severe sweating and fatigue.\", \"label\": 1, \"medication\": \"Paracetamol\"},\n",
        "    {\"text\": \"Symptoms include a fever of 38°C, sore throat, and shivering.\", \"label\": 1, \"medication\": \"Paracetamol\"},\n",
        "    {\"text\": \"Fever accompanied by a headache and muscle pain.\", \"label\": 1, \"medication\": \"Paracetamol\"},\n",
        "    {\"text\": \"The patient has a fever, feels weak, and is experiencing sweating.\", \"label\": 1, \"medication\": \"Paracetamol\"},\n",
        "\n",
        "    # Class 0 - No Fever\n",
        "    {\"text\": \"Mild dizziness and headache but no fever recorded.\", \"label\": 0, \"medication\": \"Rest and hydration\"},\n",
        "    {\"text\": \"The patient complains of congestion but denies fever.\", \"label\": 0, \"medication\": \"Rest and hydration\"},\n",
        "    {\"text\": \"No fever, but the patient has a sore throat and fatigue.\", \"label\": 0, \"medication\": \"Rest and hydration\"},\n",
        "    {\"text\": \"The patient reports weakness and tiredness but no fever.\", \"label\": 0, \"medication\": \"Rest and hydration\"},\n",
        "]\n",
        "\n",
        "# Convert to Hugging Face Dataset\n",
        "df = Dataset.from_list(data)\n",
        "\n",
        "# Split data into train and test sets\n",
        "train_test = df.train_test_split(test_size=0.2, seed=42)\n",
        "train_data = train_test[\"train\"]\n",
        "test_data = train_test[\"test\"]\n",
        "\n",
        "# Load BERT tokenizer and model\n",
        "tokenizer = BertTokenizer.from_pretrained(\"bert-base-uncased\")\n",
        "model = BertForSequenceClassification.from_pretrained(\"bert-base-uncased\", num_labels=2)  # Two labels: Fever or No Fever\n",
        "\n",
        "# Preprocess data\n",
        "def preprocess(data):\n",
        "    return tokenizer(data[\"text\"], padding=\"max_length\", truncation=True, max_length=128)\n",
        "\n",
        "train_data = train_data.map(preprocess, batched=True)\n",
        "test_data = test_data.map(preprocess, batched=True)\n",
        "\n",
        "# Set format for PyTorch\n",
        "train_data.set_format(type=\"torch\", columns=[\"input_ids\", \"attention_mask\", \"label\"])\n",
        "test_data.set_format(type=\"torch\", columns=[\"input_ids\", \"attention_mask\", \"label\"])\n",
        "\n",
        "# Define training arguments\n",
        "training_args = TrainingArguments(\n",
        "    output_dir=\"./results\",\n",
        "    evaluation_strategy=\"epoch\",\n",
        "    save_strategy=\"epoch\",\n",
        "    num_train_epochs=10,\n",
        "    per_device_train_batch_size=16,\n",
        "    per_device_eval_batch_size=16,\n",
        "    warmup_steps=300,\n",
        "    weight_decay=0.01,\n",
        "    logging_dir=\"./logs\",\n",
        "    logging_steps=10,\n",
        "    learning_rate=5e-5,  # Adjust learning rate\n",
        ")\n",
        "\n",
        "# Define compute_metrics function to calculate evaluation metrics\n",
        "def compute_metrics(p):\n",
        "    preds = np.argmax(p.predictions, axis=1)\n",
        "    precision, recall, f1, _ = precision_recall_fscore_support(p.label_ids, preds, average='binary',zero_division=1)\n",
        "    accuracy = accuracy_score(p.label_ids, preds)\n",
        "    return {\"accuracy\": accuracy,\"precision\": precision, \"recall\": recall, \"f1\": f1}\n",
        "\n",
        "# Initialize Trainer\n",
        "trainer = Trainer(\n",
        "    model=model,\n",
        "    args=training_args,\n",
        "    train_dataset=train_data,\n",
        "    eval_dataset=test_data,\n",
        "    tokenizer=tokenizer,\n",
        "    compute_metrics=compute_metrics,\n",
        ")\n",
        "\n",
        "# Train the model and keep track of the training logs\n",
        "train_result = trainer.train()\n",
        "trainer.save_model()  # Save the model\n",
        "\n",
        "# Evaluate the model\n",
        "metrics = trainer.evaluate()\n",
        "print(\"Evaluation Metrics:\", metrics)\n",
        "\n",
        "\n",
        "# Save the trained model and tokenizer\n",
        "model.save_pretrained(\"fever_detection_model\")\n",
        "tokenizer.save_pretrained(\"fever_detection_tokenizer\")\n",
        "\n",
        "# Plot accuracy vs iterations\n",
        "logs = trainer.state.log_history\n",
        "\n",
        "# Extract accuracy and steps from logs\n",
        "steps = []\n",
        "accuracies = []\n",
        "for log in logs:\n",
        "    if 'eval_accuracy' in log:\n",
        "        steps.append(log['step'])\n",
        "        accuracies.append(log['eval_accuracy'])\n",
        "\n",
        "# Plotting the graph\n",
        "plt.plot(steps, accuracies, marker='o')\n",
        "plt.xlabel(\"Steps\")\n",
        "plt.ylabel(\"Accuracy\")\n",
        "plt.title(\"Accuracy vs Steps\")\n",
        "plt.grid(True)\n",
        "plt.show()\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000,
          "referenced_widgets": [
            "c7251ae2e9cb44979702edf0e15112cf",
            "e07740fa1e4d4e4581f9e13c9f051c4c",
            "bd9045a968574336b795c6ea495741d6",
            "49fac4811f5e48af9bbf43ec2d204b13",
            "e506614ef2564fa69b4647d8611904b3",
            "82ff1d1f590143c1b9b075e182052072",
            "0a4ca7cc390c4552abfa9e779e10897f",
            "cad39de900bd4354a3c38a478243bc7d",
            "c5e71e82dff64fd5b95c1c4511293aa5",
            "aec89e645a8a419688cc38775a8633ca",
            "ab8854f49eb1448f96e99d737b71a0f0",
            "5202c29a607c44ebb64f797624f6ebe2",
            "c70de9546de04c10825c137eeb69b8b3",
            "7f0c7448110949659a2ca91e87690fd9",
            "5ec567ca313b4205af5184e60df435fb",
            "421b0adc20cc4330afb79c8c829b0bac",
            "4568c7376aba4329b01368812c02441b",
            "7ae671b9ce9a4c1d85a6314965dc169a",
            "bad42d8072844c4e936afffa72d19b5d",
            "9de191c3d6014f9e85b5bc3b7a51b0cd",
            "725432b69f5a45cfa25b6fd115aa7567",
            "4988a34b3f24414b945da5fce490b041"
          ]
        },
        "id": "KDkKmSgRR_he",
        "outputId": "5420d53f-e53d-4e50-8458-89eff4a3fd62"
      },
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.47.1)\n",
            "Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (3.2.0)\n",
            "Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.6.1)\n",
            "Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (3.10.0)\n",
            "Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.17.0)\n",
            "Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.27.1)\n",
            "Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (1.26.4)\n",
            "Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)\n",
            "Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)\n",
            "Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)\n",
            "Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)\n",
            "Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.0)\n",
            "Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.2)\n",
            "Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)\n",
            "Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (17.0.0)\n",
            "Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.3.8)\n",
            "Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)\n",
            "Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets) (3.5.0)\n",
            "Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.70.16)\n",
            "Requirement already satisfied: fsspec<=2024.9.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets) (2024.9.0)\n",
            "Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.11)\n",
            "Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.13.1)\n",
            "Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.4.2)\n",
            "Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.5.0)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.3.1)\n",
            "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (4.55.4)\n",
            "Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.4.8)\n",
            "Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (11.1.0)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (3.2.1)\n",
            "Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (2.8.2)\n",
            "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.4.4)\n",
            "Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)\n",
            "Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (24.3.0)\n",
            "Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)\n",
            "Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.1.0)\n",
            "Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.2.1)\n",
            "Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)\n",
            "Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (4.12.2)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2024.12.14)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2024.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']\n",
            "You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Map:   0%|          | 0/27 [00:00<?, ? examples/s]"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "c7251ae2e9cb44979702edf0e15112cf"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "Map:   0%|          | 0/7 [00:00<?, ? examples/s]"
            ],
            "application/vnd.jupyter.widget-view+json": {
              "version_major": 2,
              "version_minor": 0,
              "model_id": "5202c29a607c44ebb64f797624f6ebe2"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead\n",
            "  warnings.warn(\n",
            "<ipython-input-10-dfef3d97d07c>:101: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.\n",
            "  trainer = Trainer(\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": [
              "\n",
              "    <div>\n",
              "      \n",
              "      <progress value='20' max='20' style='width:300px; height:20px; vertical-align: middle;'></progress>\n",
              "      [20/20 15:35, Epoch 10/10]\n",
              "    </div>\n",
              "    <table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              " <tr style=\"text-align: left;\">\n",
              "      <th>Epoch</th>\n",
              "      <th>Training Loss</th>\n",
              "      <th>Validation Loss</th>\n",
              "      <th>Accuracy</th>\n",
              "      <th>Precision</th>\n",
              "      <th>Recall</th>\n",
              "      <th>F1</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <td>1</td>\n",
              "      <td>No log</td>\n",
              "      <td>0.670921</td>\n",
              "      <td>0.714286</td>\n",
              "      <td>0.500000</td>\n",
              "      <td>0.500000</td>\n",
              "      <td>0.500000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <td>2</td>\n",
              "      <td>No log</td>\n",
              "      <td>0.670166</td>\n",
              "      <td>0.714286</td>\n",
              "      <td>0.500000</td>\n",
              "      <td>0.500000</td>\n",
              "      <td>0.500000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <td>3</td>\n",
              "      <td>No log</td>\n",
              "      <td>0.669004</td>\n",
              "      <td>0.857143</td>\n",
              "      <td>0.666667</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.800000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <td>4</td>\n",
              "      <td>No log</td>\n",
              "      <td>0.666397</td>\n",
              "      <td>0.857143</td>\n",
              "      <td>0.666667</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.800000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <td>5</td>\n",
              "      <td>0.691100</td>\n",
              "      <td>0.662854</td>\n",
              "      <td>0.857143</td>\n",
              "      <td>0.666667</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.800000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <td>6</td>\n",
              "      <td>0.691100</td>\n",
              "      <td>0.656115</td>\n",
              "      <td>0.857143</td>\n",
              "      <td>0.666667</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.800000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <td>7</td>\n",
              "      <td>0.691100</td>\n",
              "      <td>0.648141</td>\n",
              "      <td>0.857143</td>\n",
              "      <td>0.666667</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.800000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <td>8</td>\n",
              "      <td>0.691100</td>\n",
              "      <td>0.642238</td>\n",
              "      <td>0.857143</td>\n",
              "      <td>0.666667</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.800000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <td>9</td>\n",
              "      <td>0.691100</td>\n",
              "      <td>0.636027</td>\n",
              "      <td>0.857143</td>\n",
              "      <td>0.666667</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.800000</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <td>10</td>\n",
              "      <td>0.653100</td>\n",
              "      <td>0.630468</td>\n",
              "      <td>0.857143</td>\n",
              "      <td>0.666667</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.800000</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table><p>"
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": [
              "\n",
              "    <div>\n",
              "      \n",
              "      <progress value='1' max='1' style='width:300px; height:20px; vertical-align: middle;'></progress>\n",
              "      [1/1 : < :]\n",
              "    </div>\n",
              "    "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Evaluation Metrics: {'eval_loss': 0.6304675936698914, 'eval_accuracy': 0.8571428571428571, 'eval_precision': 0.6666666666666666, 'eval_recall': 1.0, 'eval_f1': 0.8, 'eval_runtime': 4.1127, 'eval_samples_per_second': 1.702, 'eval_steps_per_second': 0.243, 'epoch': 10.0}\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<Figure size 640x480 with 1 Axes>"
            ],
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAkAAAAHHCAYAAABXx+fLAAAAOnRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjEwLjAsIGh0dHBzOi8vbWF0cGxvdGxpYi5vcmcvlHJYcgAAAAlwSFlzAAAPYQAAD2EBqD+naQAAV4xJREFUeJzt3XlclNX+B/DPzDCsAi7siIDWxSzDFVLbUym9mF01lxKX0jIpi9siJpJ5lW73Xq+3Mq1+qHXVJEvNskwk0bwumKhFmqlgpOxuIOvAnN8fOpPTDMvADM/MPJ/368XL5sx5Dt8vD8u385zzPAohhAARERGRjCilDoCIiIiovbEAIiIiItlhAURERESywwKIiIiIZIcFEBEREckOCyAiIiKSHRZAREREJDssgIiIiEh2WAARERGR7LAAIiIiItlhAUTkgN59910oFApER0dLHQr9wY8//oixY8ciNDQUrq6uCA4OxrBhw/D2228b9FuyZAm2bNkiTZBEMqDgs8CIHM+QIUNQUFCAs2fP4tSpU7jpppukDokA7Nu3D/fddx+6deuGKVOmICAgAL/99hsOHDiAM2fO4PTp0/q+HTp0wNixY7FmzRrpAiZyYE5SB0BElpWXl4d9+/Zh06ZNeOqpp7Bu3TokJydLHZZJlZWV8PDwkDqMdrN48WJ4e3vj0KFD6Nixo8F7JSUl0gRFJFO8BEbkYNatW4dOnTph5MiRGDt2LNatW2ey3+XLl/HCCy8gLCwMLi4u6Nq1K+Li4lBWVqbvU1NTg9deew1/+tOf4OrqisDAQPzlL3/BmTNnAACZmZlQKBTIzMw0GPvs2bNQKBQGsxdTp05Fhw4dcObMGYwYMQKenp547LHHAADfffcdxo0bh27dusHFxQUhISF44YUXUF1dbRT3zz//jEcffRS+vr5wc3NDREQEXn31VQDArl27oFAosHnzZqPj1q9fD4VCgf3795v8enz//fdQKBT48MMPjd775ptvoFAo8OWXXwIAKioq8Pzzz+u/dn5+fhg2bBiys7NNjq1z5swZ3HrrrUbFDwD4+fnp/1uhUKCyshIffvghFAoFFAoFpk6dqn///PnzmD59Ovz9/eHi4oJbb70Vq1atMhhPd27S0tIwb948BAQEwMPDA6NGjcJvv/1m0PfUqVMYM2YMAgIC4Orqiq5du2LChAm4cuVKk/kQ2TPOABE5mHXr1uEvf/kLnJ2dMXHiRKxYsQKHDh3CwIED9X2uXr2Ku+66CydOnMD06dPRr18/lJWVYevWrTh37hx8fHzQ0NCAP//5z8jIyMCECRMwZ84cVFRUID09HTk5OejRo4fZsdXX1yMmJgZ33nkn/vnPf8Ld3R0AsHHjRlRVVWHWrFno0qULsrKy8Pbbb+PcuXPYuHGj/vgffvgBd911F9RqNWbOnImwsDCcOXMGX3zxBRYvXox7770XISEhWLduHR555BGjr0uPHj0waNAgk7ENGDAA3bt3xyeffIIpU6YYvJeWloZOnTohJiYGAPD000/j008/RXx8PHr16oULFy5g7969OHHiBPr169do/qGhodi/fz9ycnJw2223Ndrvv//9L5588klERUVh5syZAKD/ehcXF+OOO+6AQqFAfHw8fH198fXXX+OJJ55AeXk5nn/+eYOxFi9eDIVCgVdeeQUlJSVYtmwZhg4diqNHj8LNzQ11dXWIiYlBbW0tnn32WQQEBOD8+fP48ssvcfnyZXh7ezcaJ5FdE0TkML7//nsBQKSnpwshhNBqtaJr165izpw5Bv0WLFggAIhNmzYZjaHVaoUQQqxatUoAEEuXLm20z65duwQAsWvXLoP38/LyBACxevVqfduUKVMEADF37lyj8aqqqozaUlJShEKhEL/++qu+7e677xaenp4GbTfGI4QQiYmJwsXFRVy+fFnfVlJSIpycnERycrLR57lRYmKiUKvV4uLFi/q22tpa0bFjRzF9+nR9m7e3t5g9e3aTY5myY8cOoVKphEqlEoMGDRIvv/yy+Oabb0RdXZ1RXw8PDzFlyhSj9ieeeEIEBgaKsrIyg/YJEyYIb29v/ddSd26Cg4NFeXm5vt8nn3wiAIj//Oc/Qgghjhw5IgCIjRs3mp0PkT3jJTAiB7Ju3Tr4+/vjvvvuA3DtUsr48eOxYcMGNDQ06Pt99tlniIyMNJol0R2j6+Pj44Nnn3220T6tMWvWLKM2Nzc3/X9XVlairKwMgwcPhhACR44cAQCUlpZiz549mD59Orp169ZoPHFxcaitrcWnn36qb0tLS0N9fT0ef/zxJmMbP348NBoNNm3apG/bsWMHLl++jPHjx+vbOnbsiIMHD6KgoKCFWV8zbNgw7N+/H6NGjcKxY8fw5ptvIiYmBsHBwdi6dWuzxwsh8NlnnyE2NhZCCJSVlek/YmJicOXKFaPLcHFxcfD09NS/Hjt2LAIDA/HVV18BgH6G55tvvkFVVZVZ+RDZMxZARA6ioaEBGzZswH333Ye8vDycPn0ap0+fRnR0NIqLi5GRkaHve+bMmSYvwej6REREwMnJclfKnZyc0LVrV6P2/Px8TJ06FZ07d0aHDh3g6+uLe+65BwD061Byc3MBoNm4e/bsiYEDBxqsfVq3bh3uuOOOZnfDRUZGomfPnkhLS9O3paWlwcfHB/fff7++7c0330ROTg5CQkIQFRWF1157TR9fcwYOHIhNmzbh0qVLyMrKQmJiIioqKjB27FgcP368yWNLS0tx+fJlvP/++/D19TX4mDZtGgDjxdQ333yzwWuFQoGbbroJZ8+eBQCEh4cjISEB//d//wcfHx/ExMRg+fLlXP9DDo8FEJGD+Pbbb1FYWIgNGzbg5ptv1n88+uijANDoYui2aGwm6MbZphu5uLhAqVQa9R02bBi2bduGV155BVu2bEF6erp+AbVWqzU7rri4OOzevRvnzp3DmTNncODAgWZnf3TGjx+PXbt2oaysDLW1tdi6dSvGjBljUAg++uijyM3Nxdtvv42goCD84x//wK233oqvv/66xTE6Oztj4MCBWLJkCVasWAGNRmOw3skU3dfi8ccfR3p6usmPIUOGtDgGnX/961/44YcfMG/ePFRXV+O5557DrbfeinPnzpk9FpG94CJoIgexbt06+Pn5Yfny5Ubvbdq0CZs3b8bKlSvh5uaGHj16ICcnp8nxevTogYMHD0Kj0UCtVpvs06lTJwDXdpTd6Ndff21x3D/++CN++eUXfPjhh4iLi9O3p6enG/Tr3r07ADQbNwBMmDABCQkJ+Pjjj1FdXQ21Wm1wCasp48ePx8KFC/HZZ5/B398f5eXlmDBhglG/wMBAPPPMM3jmmWdQUlKCfv36YfHixXjooYda9HluNGDAAABAYWGhvs1Ucenr6wtPT080NDRg6NChLRr71KlTBq+FEDh9+jRuv/12g/bevXujd+/emD9/Pvbt24chQ4Zg5cqV+Nvf/mZuOkR2gTNARA6guroamzZtwp///GeMHTvW6CM+Ph4VFRX6dSZjxozBsWPHTG4XF9fvjTpmzBiUlZXhnXfeabRPaGgoVCoV9uzZY/D+u+++2+LYVSqVwZi6//7Pf/5j0M/X1xd33303Vq1ahfz8fJPx6Pj4+OChhx7C2rVrsW7dOjz44IPw8fFpUTy33HILevfujbS0NKSlpSEwMBB33323/v2Ghgajy0N+fn4ICgpCbW1tk2Pv2rXLKFYA+vU4ERER+jYPDw+jwlKlUmHMmDH47LPPTBaCpaWlRm0fffQRKioq9K8//fRTFBYW6gu18vJy1NfXGxzTu3dvKJXKZvMhsmecASJyAFu3bkVFRQVGjRpl8v077rgDvr6+WLduHcaPH4+XXnoJn376KcaNG4fp06ejf//+uHjxIrZu3YqVK1ciMjIScXFx+Oijj5CQkICsrCzcddddqKysxM6dO/HMM8/g4Ycfhre3N8aNG4e3334bCoUCPXr0wJdffmnWTf169uyJHj164MUXX8T58+fh5eWFzz77DJcuXTLq+9Zbb+HOO+9Ev379MHPmTISHh+Ps2bPYtm0bjh49atA3Li4OY8eOBQAsWrSo5V9MXJsFWrBgAVxdXfHEE08YXLarqKhA165dMXbsWERGRqJDhw7YuXMnDh06hH/9619Njvvss8+iqqoKjzzyCHr27Im6ujrs27cPaWlpCAsL06/jAYD+/ftj586dWLp0KYKCghAeHo7o6Gi88cYb2LVrF6KjozFjxgz06tULFy9eRHZ2Nnbu3ImLFy8afM7OnTvjzjvvxLRp01BcXIxly5bhpptuwowZMwBcu3QaHx+PcePG4U9/+hPq6+vx3//+V19sETksqbafEZHlxMbGCldXV1FZWdlon6lTpwq1Wq3fPn3hwgURHx8vgoODhbOzs+jatauYMmWKwfbqqqoq8eqrr4rw8HChVqtFQECAGDt2rDhz5oy+T2lpqRgzZoxwd3cXnTp1Ek899ZTIyckxuQ3ew8PDZGzHjx8XQ4cOFR06dBA+Pj5ixowZ4tixY0ZjCCFETk6OeOSRR0THjh2Fq6uriIiIEElJSUZj1tbWik6dOglvb29RXV3dki+j3qlTpwQAAUDs3bvXaNyXXnpJREZGCk9PT+Hh4SEiIyPFu+++2+y4X3/9tZg+fbro2bOn6NChg3B2dhY33XSTePbZZ0VxcbFB359//lncfffdws3NTQAw2BJfXFwsZs+eLUJCQvTn5YEHHhDvv/++vo9uG/zHH38sEhMThZ+fn3BzcxMjR440uI1Abm6umD59uujRo4dwdXUVnTt3Fvfdd5/YuXOnWV8zInvDZ4ERkUOqr69HUFAQYmNjkZqaKnU47S4zMxP33XcfNm7cqJ8JI6LfcQ0QETmkLVu2oLS01GBhNRGRDtcAEZFDOXjwIH744QcsWrQIffv21d9PiIjoRpwBIiKHsmLFCsyaNQt+fn746KOPpA6HiGwU1wARERGR7HAGiIiIiGSHBRARERHJDhdBm6DValFQUABPT882PfWaiIiI2o8QAhUVFQgKCjJ67uAfsQAyoaCgACEhIVKHQURERK3w22+/oWvXrk32YQFkgqenJ4BrX0AvLy9JY9FoNNixYweGDx/e6AMpHZVcc5dr3gBzl2Pucs0bYO7WyL28vBwhISH6v+NNYQFkgu6yl5eXl00UQO7u7vDy8pLlD4gcc5dr3gBzl2Pucs0bYO7WzL0ly1e4CJqIiIhkhwUQERERyQ4LICIiIpIdyQug5cuXIywsDK6uroiOjkZWVlaT/ZctW4aIiAi4ubkhJCQEL7zwAmpqagz6nD9/Ho8//ji6dOkCNzc39O7dG99//7010yAiIiI7Iuki6LS0NCQkJGDlypWIjo7GsmXLEBMTg5MnT8LPz8+o//r16zF37lysWrUKgwcPxi+//IKpU6dCoVBg6dKlAIBLly5hyJAhuO+++/D111/D19cXp06dQqdOndo7PSIiIrJRkhZAS5cuxYwZMzBt2jQAwMqVK7Ft2zasWrUKc+fONeq/b98+DBkyBJMmTQIAhIWFYeLEiTh48KC+z9///neEhIRg9erV+rbw8HArZ0JERET2RLICqK6uDocPH0ZiYqK+TalUYujQodi/f7/JYwYPHoy1a9ciKysLUVFRyM3NxVdffYXJkyfr+2zduhUxMTEYN24cdu/ejeDgYDzzzDOYMWNGo7HU1taitrZW/7q8vBzAtW16Go2mram2ie7zSx2HFOSau1zzBpj7jf/KhVzzBpj7jf9aetyWkOxp8AUFBQgODsa+ffswaNAgffvLL7+M3bt3G8zq3Oitt97Ciy++CCEE6uvr8fTTT2PFihX6911dXQEACQkJGDduHA4dOoQ5c+Zg5cqVmDJliskxX3vtNSxcuNCoff369XB3d29LmkRERNROqqqqMGnSJFy5cqXZ+/jZ1Y0QMzMzsWTJErz77ruIjo7G6dOnMWfOHCxatAhJSUkArj3Ha8CAAViyZAkAoG/fvsjJyWmyAEpMTERCQoL+te5OksOHD7eJGyGmp6dj2LBhsrxRlhxzl2veAHOXY+5yzRtg7tbIXXcFpyUkK4B8fHygUqlQXFxs0F5cXIyAgACTxyQlJWHy5Ml48sknAQC9e/dGZWUlZs6ciVdffRVKpRKBgYHo1auXwXG33HILPvvss0ZjcXFxgYuLi1G7Wq22mW9KW4qlvVkr9watQFbeRZRU1MDP0xVR4Z2hUtrOw29bmret59FSDVqB7LyLOFymQJdzFRh0k5/d5tGW82ErP+vt/X0l159zQH4/63X1Wqw9dBbf5SlRfOg8pg7pAWcny2xKN+d7SLICyNnZGf3790dGRgZGjx4N4NrsTUZGBuLj400eU1VVZfR0V5VKBeDaE2ABYMiQITh58qRBn19++QWhoaEWzoDs2facQiz84jgKr/x+C4VAb1ckx/bCg7cFShiZeRwzDxU+OvW9A+RxDfOQjqPkAThOLilfHccH3+VBKwBAie++/gVvbP8FM+4KR+KIXs0dblGS3gcoISEBH3zwAT788EOcOHECs2bNQmVlpX5XWFxcnMEi6djYWKxYsQIbNmxAXl4e0tPTkZSUhNjYWH0h9MILL+DAgQNYsmQJTp8+jfXr1+P999/H7NmzJcmRbM/2nELMWptt8IsEAIqu1GDW2mxszymUKDLzMA/bwjxsi6PkAThOLilfHcd7e3TFz++0AnhvTx5SvjrervFIugZo/PjxKC0txYIFC1BUVIQ+ffpg+/bt8Pf3BwDk5+cbzPjMnz8fCoUC8+fPx/nz5+Hr64vY2FgsXrxY32fgwIHYvHkzEhMT8frrryM8PBzLli3DY4891u75ke1p0Aos/OI4TK3817Ut+Pwn3BLoJdnUcn19PS7WAucvV8PJyfSOhgatQNLnP9l0Hi3BPH7XkvNubVKcD2vkbS/fV3L6Wa+r1+KD7/Ka7PPBd3n46/CeFrsc1hzJdoHZsvLycnh7e7doFbm1aTQafPXVVxgxYoRNrAtoT9bIff+ZC5j4wQGLjEVERJaVNPIWPHFX91Yfb87fb7vaBUbUViUVNc13AuCkVEj6f1PahgYor1/WNaVBK1D/x3lkE6TOoznMw1Bz593apDofls7bnr6v5PKzrmnQGl36MuXXi1XWD+Y6FkAkK36eri3q998nojGoRxcrR2Pa7zNfMY3OfLV0JkvKPFqCefyuJefd2qQ4H9bI216+r+T0s576XS4WbTvRbL/Qzu137z3JH4ZK1J6iwjsj0NsVjf1/kgLXdlZEhXduz7DMxjxsC/OwLY6SB+A4uUweFIbmJqiUimv92gsLIJIVlVKB5FjTWy11P5vJsb1seioZMMzjj5Eyj/bHPGyLo+QBOE4uzk5KzLir6edyzrgrvN0WQAMsgEiGHrwtECse72f0CyPA2xUrHu9nN/fU0OUR4G14WY95SIN52BZHyQNwnFwSR/TCU3eHG80EKRXAU3e3/32AuAaIZGlYrwAorm8ifW1UL0T4e9nlXVUfvC0Qw3oF2P3dYXV57D9dgh3fHcTwu6Lt8k7QjnY+mIftcJRcEkf0wl+H98Sa/53Bd0d+xl19e1r0TtDmYAFEsnTuUhXqtYCLkxJxd4RBaWe/RG6kUipsevFjS6mUCkSHd8aFEwLRdviLXceRzgfzsC2OkouzkxLTBofB//JxjBgcBrUExQ/AS2AkU7lllQCAcB8Puy5+iIiodVgAkSzllf5eABERkfywACJZyitjAUREJGcsgEiWWAAREckbCyCSJV0B1N23g8SREBGRFFgAkexU1zXg/OVqAEB3zgAREckSCyCSnbMXrs3+dHRXo5OHs8TREBGRFFgAkexw/Q8REbEAItlhAURERCyASHZyr98DiOt/iIjkiwUQyU5e2VUA3AFGRCRnLIBIdnJ5CYyISPZYAJGsXKqsw+UqDQAgrAsLICIiuWIBRLKim/0J8naFm7NK4miIiEgqLIBIVvQ7wHw5+0NEJGcsgEhWdAuguf6HiEjeWACRrOifAebDHWBERHLGAohkRXcPIF4CIyKSNxZAJBtarbhhBogFEBGRnLEAItkoLK9Bbb0WapUCwR3dpA6HiIgkxAKIZCPv+uWvbp3d4aTitz4RkZzxrwDJBh+BQUREOiyASDZyuf6HiIiuYwFEsqHfAcYCiIhI9lgAkWzk8SGoRER0HQsgkoXa+gacu1QFgPcAIiIiFkAkE79drIJWAB1cnODbwUXqcIiISGIsgEgWdOt/uvt6QKFQSBwNERFJjQUQyUIu1/8QEdENbKIAWr58OcLCwuDq6oro6GhkZWU12X/ZsmWIiIiAm5sbQkJC8MILL6CmpsZk3zfeeAMKhQLPP/+8FSIne5HHHWBERHQDyQugtLQ0JCQkIDk5GdnZ2YiMjERMTAxKSkpM9l+/fj3mzp2L5ORknDhxAqmpqUhLS8O8efOM+h46dAjvvfcebr/9dmunQTaOO8CIiOhGkhdAS5cuxYwZMzBt2jT06tULK1euhLu7O1atWmWy/759+zBkyBBMmjQJYWFhGD58OCZOnGg0a3T16lU89thj+OCDD9CpU6f2SIVs2O83QeRdoImICHCS8pPX1dXh8OHDSExM1LcplUoMHToU+/fvN3nM4MGDsXbtWmRlZSEqKgq5ubn46quvMHnyZIN+s2fPxsiRIzF06FD87W9/azKO2tpa1NbW6l+Xl5cDADQaDTQaTWvTswjd55c6DilYKveKGg3Krl47v8Hezjb/teQ5Z+5yIte8AeZ+47+WHrclJC2AysrK0NDQAH9/f4N2f39//PzzzyaPmTRpEsrKynDnnXdCCIH6+no8/fTTBpfANmzYgOzsbBw6dKhFcaSkpGDhwoVG7Tt27IC7u7sZGVlPenq61CFIpq25518FACd4qQW++3aHRWJqDzzn8iTX3OWaN8DcLamqqqrFfSUtgFojMzMTS5Yswbvvvovo6GicPn0ac+bMwaJFi5CUlITffvsNc+bMQXp6OlxdXVs0ZmJiIhISEvSvy8vLERISguHDh8PLy8taqbSIRqNBeno6hg0bBrVaLWks7c1SuX9+rBD48Uf0DO6MESMGWjBC6+A5Z+5yyl2ueQPM3Rq5667gtISkBZCPjw9UKhWKi4sN2ouLixEQEGDymKSkJEyePBlPPvkkAKB3796orKzEzJkz8eqrr+Lw4cMoKSlBv3799Mc0NDRgz549eOedd1BbWwuVSmUwpouLC1xcjG+Op1arbeab0pZiaW9tzT3/0rUdgj38OtjV15DnnLnLiVzzBpi7JXM3ZyxJF0E7Ozujf//+yMjI0LdptVpkZGRg0KBBJo+pqqqCUmkYtq6gEULggQcewI8//oijR4/qPwYMGIDHHnsMR48eNSp+yPFxBxgREf2R5JfAEhISMGXKFAwYMABRUVFYtmwZKisrMW3aNABAXFwcgoODkZKSAgCIjY3F0qVL0bdvX/0lsKSkJMTGxkKlUsHT0xO33Xabwefw8PBAly5djNpJHvLKrgIAwrkDjIiIrpO8ABo/fjxKS0uxYMECFBUVoU+fPti+fbt+YXR+fr7BjM/8+fOhUCgwf/58nD9/Hr6+voiNjcXixYulSoFsmBCCN0EkIiIjkhdAABAfH4/4+HiT72VmZhq8dnJyQnJyMpKTk1s8/h/HIPkorahFZV0DVEoFunW2jR19REQkPclvhEhkTWeuz/6EdHKDsxO/3YmI6Br+RSCHxgXQRERkCgsgcmhcAE1ERKawACKHpp8B8uUMEBER/Y4FEDm03x+CygKIiIh+xwKIHFZ9gxb5F649F6Y7Z4CIiOgGLIDIYf12qRr1WgE3tQr+ni17LhwREckDCyByWLoF0GE+HlAqFRJHQ0REtoQFEDms3FKu/yEiItNYAJHD4j2AiIioMSyAyGHpCiAugCYioj9iAUQOizNARETUGBZA5JCq6upReKUGAAsgIiIyxgKIHJJu9qezhzM6ujtLHA0REdkaFkDkkHj5i4iImsICiBxSXikLICIiahwLIHJI3AFGRERNYQFEDukMH4JKRERNYAFEDkcIgbzSa4/BCPfpIHE0RERki1gAkcO5WFmH8pp6KBRAaBd3qcMhIiIbxAKIHI5u/U+Qtxtc1SqJoyEiIlvEAogcTi4XQBMRUTNYAJHDyeMCaCIiagYLIHI4ufoF0CyAiIjINBZA5HD0d4H25Q4wIiIyjQUQOZQGrcDZC1UAeAmMiIgaxwKIHErB5WrU1WvhrFIiqKOb1OEQEZGNYgFEDkV3+Su0iztUSoXE0RARka1iAUQOhc8AIyKilmABRA4ll4/AICKiFmABRA4ll/cAIiKiFmABRA7l9y3wLICIiKhxLIDIYdRoGnD+cjUA3gSRiIiaxgKIHEb+xSoIAXi6OqGLh7PU4RARkQ1jAUQOI7dUtwOsAxQKboEnIqLGsQAih5Fbdm0HGBdAExFRc2yiAFq+fDnCwsLg6uqK6OhoZGVlNdl/2bJliIiIgJubG0JCQvDCCy+gpqZG/35KSgoGDhwIT09P+Pn5YfTo0Th58qS10yCJ5V2fAeL6HyIiao7kBVBaWhoSEhKQnJyM7OxsREZGIiYmBiUlJSb7r1+/HnPnzkVycjJOnDiB1NRUpKWlYd68efo+u3fvxuzZs3HgwAGkp6dDo9Fg+PDhqKysbK+0SAL6HWAsgIiIqBlOUgewdOlSzJgxA9OmTQMArFy5Etu2bcOqVaswd+5co/779u3DkCFDMGnSJABAWFgYJk6ciIMHD+r7bN++3eCYNWvWwM/PD4cPH8bdd99txWxISiyAiIiopSQtgOrq6nD48GEkJibq25RKJYYOHYr9+/ebPGbw4MFYu3YtsrKyEBUVhdzcXHz11VeYPHlyo5/nypUrAIDOnTubfL+2tha1tbX61+Xl5QAAjUYDjUZjdl6WpPv8UschBXNyv1KtwYXKOgBAV29nu/568ZwzdzmRa94Ac7/xX0uP2xIKIYSw6Gc3Q0FBAYKDg7Fv3z4MGjRI3/7yyy9j9+7dBrM6N3rrrbfw4osvQgiB+vp6PP3001ixYoXJvlqtFqNGjcLly5exd+9ek31ee+01LFy40Kh9/fr1cHd3b0Vm1N5+rQCW5jjB21ng9f4NUodDREQSqKqqwqRJk3DlyhV4eXk12VfyS2DmyszMxJIlS/Duu+8iOjoap0+fxpw5c7Bo0SIkJSUZ9Z89ezZycnIaLX4AIDExEQkJCfrX5eXlCAkJwfDhw5v9AlqbRqNBeno6hg0bBrVaLWks7c2c3LccLQBycnBLcGeMGDGwnSK0Dp5z5i6n3OWaN8DcrZG77gpOS0haAPn4+EClUqG4uNigvbi4GAEBASaPSUpKwuTJk/Hkk08CAHr37o3KykrMnDkTr776KpTK39d1x8fH48svv8SePXvQtWvXRuNwcXGBi4uLUbtarbaZb0pbiqW9tST3/EvXdgF29/N0mK8TzzlzlxO55g0wd0vmbs5Yku4Cc3Z2Rv/+/ZGRkaFv02q1yMjIMLgkdqOqqiqDIgcAVCoVAEB3NU8Igfj4eGzevBnffvstwsPDrZQB2Qo+BJWIiMwh+SWwhIQETJkyBQMGDEBUVBSWLVuGyspK/a6wuLg4BAcHIyUlBQAQGxuLpUuXom/fvvpLYElJSYiNjdUXQrNnz8b69evx+eefw9PTE0VFRQAAb29vuLm5SZMoWRXvAUREROaQvAAaP348SktLsWDBAhQVFaFPnz7Yvn07/P39AQD5+fkGMz7z58+HQqHA/Pnzcf78efj6+iI2NhaLFy/W99EtiL733nsNPtfq1asxdepUq+dE7UsIod8C3923g8TREBGRPZC8AAKurdWJj483+V5mZqbBaycnJyQnJyM5ObnR8STc2EYSKCqvQbWmAU5KBbp24gwfERE1T/I7QRO1le7yV7fO7lCr+C1NRETN418Lsnu5vAM0ERGZiQUQ2T0+AoOIiMzFAojsnr4A8mUBRERELcMCiOyefgeYD3eAERFRy7AAIrtWV69F/sUqAEB3zgAREVELsQAiu/bbpSo0aAXcnVXw8zR+nAkREZEpLIDIrt14B2iFQiFxNEREZC9YAJFd4w4wIiJqDRZAZNf4EFQiImoNFkBk1/LKrgLgM8CIiMg8LIDIruXyKfBERNQKLIDIbl2trUdJRS0AIIwFEBERmYEFENmts9fX//h0cIa3m1riaIiIyJ6wACK7xYegEhFRa7EAIruVx/U/RETUSiyAyG5xBxgREbUWCyCyW7wERkRErcUCiOySEEJ/CYw3QSQiInOxACK7VHa1DhW19VAogG5d3KUOh4iI7AwLILJLumeAde3kBhcnlcTREBGRvWEBRHZJvwDahwugiYjIfCyAyC5xATQREbUFCyCyS7pngHX3ZQFERETmYwFEdimPM0BERNQGLIDI7jRoBX69wAKIiIhajwUQ2Z3zl6qhaRBwcVIiyNtN6nCIiMgOsQAiu5N7fQdYuI8HlEqFxNEQEZE9YgFEdieXD0ElIqI2YgFEdocLoImIqK1YAJHdYQFERERtxQKI7I6uAOI9gIiIqLVYAJFdqdE04PzlagBAOB+DQURErcQCiOzK2ev3/+norkZnD2eJoyEiInvFAojsCneAERGRJbAAIrvCBdBERGQJNlEALV++HGFhYXB1dUV0dDSysrKa7L9s2TJERETAzc0NISEheOGFF1BTU9OmMck+6B+CygKIiIjaQPICKC0tDQkJCUhOTkZ2djYiIyMRExODkpISk/3Xr1+PuXPnIjk5GSdOnEBqairS0tIwb968Vo9J9iNPfxdoLoAmIqLWk7wAWrp0KWbMmIFp06ahV69eWLlyJdzd3bFq1SqT/fft24chQ4Zg0qRJCAsLw/DhwzFx4kSDGR5zxyT7wUtgRERkCU5SfvK6ujocPnwYiYmJ+jalUomhQ4di//79Jo8ZPHgw1q5di6ysLERFRSE3NxdfffUVJk+e3Ooxa2trUVtbq39dXl4OANBoNNBoNG3Osy10n1/qOKTwx9wvVdXhUtW1/+7q7eywXxOec+YuJ3LNG2DuN/5r6XFbQtICqKysDA0NDfD39zdo9/f3x88//2zymEmTJqGsrAx33nknhBCor6/H008/rb8E1poxU1JSsHDhQqP2HTt2wN3dvTWpWVx6errUIUhGl3teBQA4oaOzwK6d30gaU3vgOZcnueYu17wB5m5JVVVVLe4raQHUGpmZmViyZAneffddREdH4/Tp05gzZw4WLVqEpKSkVo2ZmJiIhIQE/evy8nKEhIRg+PDh8PLyslToraLRaJCeno5hw4ZBrVZLGkt7+2Pum46cB3J+Qq+uXTBixACpw7MannPmLqfc5Zo3wNytkbvuCk5LSFoA+fj4QKVSobi42KC9uLgYAQEBJo9JSkrC5MmT8eSTTwIAevfujcrKSsycOROvvvpqq8Z0cXGBi4uLUbtarbaZb0pbiqW96XLPv3Rtp193vw6y+FrwnDN3OZFr3gBzt2Tu5owl6SJoZ2dn9O/fHxkZGfo2rVaLjIwMDBo0yOQxVVVVUCoNw1apVAAAIUSrxiT78PsCaO4AIyKitpH8ElhCQgKmTJmCAQMGICoqCsuWLUNlZSWmTZsGAIiLi0NwcDBSUlIAALGxsVi6dCn69u2rvwSWlJSE2NhYfSHU3Jhkn3gPICIishSzC6CwsDBMnz4dU6dORbdu3docwPjx41FaWooFCxagqKgIffr0wfbt2/WLmPPz8w1mfObPnw+FQoH58+fj/Pnz8PX1RWxsLBYvXtziMcn+aLVC/xwwPgWeiIjayuwC6Pnnn8eaNWvw+uuv47777sMTTzyBRx55xOQampaKj49HfHy8yfcyMzMNXjs5OSE5ORnJycmtHpPsT2F5DWo0WqhVCgR3dJM6HCIisnNmrwF6/vnncfToUWRlZeGWW27Bs88+i8DAQMTHxyM7O9saMRIh7/rlr26d3eGkkvz+nUREZOda/ZekX79+eOutt1BQUIDk5GT83//9HwYOHIg+ffpg1apVEEJYMk6SOT4Cg4iILKnVi6A1Gg02b96M1atXIz09HXfccQeeeOIJnDt3DvPmzcPOnTuxfv16S8ZKMpZbxvU/RERkOWYXQNnZ2Vi9ejU+/vhjKJVKxMXF4d///jd69uyp7/PII49g4MCBFg2U5E23BZ47wIiIyBLMLoAGDhyIYcOGYcWKFRg9erTJmw6Fh4djwoQJFgmQCOBDUImIyLLMLoByc3MRGhraZB8PDw+sXr261UER3ai2XovfLl57vks4L4EREZEFmL0IuqSkBAcPHjRqP3jwIL7//nuLBEV0o98uVkErgA4uTvDt0PrbLRAREemYXQDNnj0bv/32m1H7+fPnMXv2bIsERXSjsxeuz/74eEChUEgcDREROQKzC6Djx4+jX79+Ru19+/bF8ePHLRIU0Y3yLnD9DxERWZbZBZCLi4vRk9YBoLCwEE5Okj9ajBzQ2bJrM0DcAk9ERJZidgE0fPhwJCYm4sqVK/q2y5cvY968eRg2bJhFgyMCfr8HEGeAiIjIUsyesvnnP/+Ju+++G6Ghoejbty8A4OjRo/D398d///tfiwdIpFsD1J13gSYiIgsxuwAKDg7GDz/8gHXr1uHYsWNwc3PDtGnTMHHiRJP3BCJqi+p6oOxqHQAgzMdd4miIiMhRtGrRjoeHB2bOnGnpWIiMlNZc+9fX0wWeriywiYjIMlq9avn48ePIz89HXV2dQfuoUaPaHBSRTkn1tW3vXP9DRESW1Ko7QT/yyCP48ccfoVAo9E99192fpaGhwbIRkqyV1lz7vurBHWBERGRBZu8CmzNnDsLDw1FSUgJ3d3f89NNP2LNnDwYMGIDMzEwrhEhyVlJ97V/OABERkSWZPQO0f/9+fPvtt/Dx8YFSqYRSqcSdd96JlJQUPPfcczhy5Ig14iSZKqnRXQLjDjAiIrIcs2eAGhoa4OnpCQDw8fFBQUEBACA0NBQnT560bHQka0IIlHIGiIiIrMDsGaDbbrsNx44dQ3h4OKKjo/Hmm2/C2dkZ77//Prp3726NGEmmSq/WoVargFIBdOvMLfBERGQ5ZhdA8+fPR2XltTvzvv766/jzn/+Mu+66C126dEFaWprFAyT5yrt+B+iundzg7GT2ZCUREVGjzC6AYmJi9P9900034eeff8bFixfRqVMnPqmbLOrGp8ATERFZkln/W63RaODk5IScnByD9s6dO7P4IYvTzQCFd+HlLyIisiyzCiC1Wo1u3brxXj/ULvKuPwU+jDNARERkYWYvrHj11Vcxb948XLx40RrxEOmdvcAZICIisg6z1wC98847OH36NIKCghAaGgoPD8P/O8/OzrZYcCRf9Q1a5F+8tgeea4CIiMjSzC6ARo8ebYUwiAydu1SNeq2AWing7+kidThERORgzC6AkpOTrREHkQHdAmg/V0Cp5AJ7IiKyLN5chWzSmdKrAABfNyFxJERE5IjMngFSKpVNbnnnDjGyhBtngIiIiCzN7AJo8+bNBq81Gg2OHDmCDz/8EAsXLrRYYCRvugKIM0BERGQNZhdADz/8sFHb2LFjceuttyItLQ1PPPGERQIjeft9BogFEBERWZ7F1gDdcccdyMjIsNRwJGNVdfUovFIDAPDlJTAiIrICixRA1dXVeOuttxAcHGyJ4UjmdLM/ndzV8FBLHAwRETkksy+B/fGhp0IIVFRUwN3dHWvXrrVocCRP+meA+XgAqJY2GCIickhmF0D//ve/DQogpVIJX19fREdHo1OnThYNjuQpr/RaARTGR2AQEZGVmH0JbOrUqZgyZYr+Y/LkyXjwwQfbVPwsX74cYWFhcHV1RXR0NLKyshrte++990KhUBh9jBw5Ut/n6tWriI+PR9euXeHm5oZevXph5cqVrY6P2hefAk9ERNZmdgG0evVqbNy40ah948aN+PDDD80OIC0tDQkJCUhOTkZ2djYiIyMRExODkpISk/03bdqEwsJC/UdOTg5UKhXGjRun75OQkIDt27dj7dq1OHHiBJ5//nnEx8dj69atZsdH7S/3egHEp8ATEZG1mF0ApaSkwMfHx6jdz88PS5YsMTuApUuXYsaMGZg2bZp+psbd3R2rVq0y2b9z584ICAjQf6Snp8Pd3d2gANq3bx+mTJmCe++9F2FhYZg5cyYiIyObnFki2yCEQO71u0B39+EMEBERWYfZa4Dy8/MRHh5u1B4aGor8/Hyzxqqrq8Phw4eRmJiob1MqlRg6dCj279/fojFSU1MxYcIEg6fSDx48GFu3bsX06dMRFBSEzMxM/PLLL/j3v/9tcoza2lrU1tbqX5eXlwO4dpNHjUZjVk6Wpvv8UsfRXi5U1qG8ph4KBRDoqcZpyCd3Hbmd8xsxd/nlLte8AeZ+47+WHrclzC6A/Pz88MMPPyAsLMyg/dixY+jSpYtZY5WVlaGhoQH+/v4G7f7+/vj555+bPT4rKws5OTlITU01aH/77bcxc+ZMdO3aFU5OTlAqlfjggw9w9913mxwnJSXF5F2sd+zYAXd325iFSE9PlzqEdpFbDgBO6OQs8F3mtwDkk/sfyTVvgLnLkVzzBpi7JVVVVbW4r9kF0MSJE/Hcc8/B09NTX1Ds3r0bc+bMwYQJE8wdrk1SU1PRu3dvREVFGbS//fbbOHDgALZu3YrQ0FDs2bMHs2fPRlBQEIYOHWo0TmJiIhISEvSvy8vLERISguHDh8PLy8vqeTRFo9EgPT0dw4YNg1rt+DfF+TT7PPDTT7ilqw+GDbtdVrnryO2c34i5yy93ueYNMHdr5K67gtMSZhdAixYtwtmzZ/HAAw/Ayena4VqtFnFxcWavAfLx8YFKpUJxcbFBe3FxMQICApo8trKyEhs2bMDrr79u0F5dXY158+Zh8+bN+p1ht99+O44ePYp//vOfJgsgFxcXuLi4GLWr1Wqb+aa0pVisKf/StTtA9/DroM9XLrn/kVzzBpi7HHOXa94Ac7dk7uaMZfYiaGdnZ6SlpeHkyZNYt24dNm3ahDNnzmDVqlVwdnY2e6z+/fsbPEJDq9UiIyMDgwYNavLYjRs3ora2Fo8//rhBu27djlJpmJpKpYJWqzUrPmp/unsAhXMHGBERWZHZM0A6N998M26++eY2B5CQkIApU6ZgwIABiIqKwrJly1BZWYlp06YBAOLi4hAcHIyUlBSD41JTUzF69GijdUdeXl6455578NJLL8HNzQ2hoaHYvXs3PvroIyxdurTN8ZJ16e4B1N23g8SREBGRIzO7ABozZgyioqLwyiuvGLS/+eabOHTokMl7BDVl/PjxKC0txYIFC1BUVIQ+ffpg+/bt+oXR+fn5RrM5J0+exN69e7Fjxw6TY27YsAGJiYl47LHHcPHiRYSGhmLx4sV4+umnzYqN2leDViDvwvUCiDNARERkRWYXQHv27MFrr71m1P7QQw/hX//6V6uCiI+PR3x8vMn3MjMzjdoiIiIghGh0vICAAKxevbpVsZB0Ci5Xo65eC2eVEkEd3aBtqJc6JCIiclBmrwG6evWqybU+arXarNXXRH+ku/wV2sUdKqWimd5EREStZ3YB1Lt3b6SlpRm1b9iwAb169bJIUCRPhk+BJyIish6zL4ElJSXhL3/5C86cOYP7778fAJCRkYH169fj008/tXiAJB/6AsiXBRAREVmX2QVQbGwstmzZgiVLluDTTz+Fm5sbIiMj8e2336Jz587WiJFkQvcQ1B4+3AFGRETW1apt8CNHjtTfZLC8vBwff/wxXnzxRRw+fBgNDQ0WDZDkQ/cQVM4AERGRtZm9Bkhnz549mDJlCoKCgvCvf/0L999/Pw4cOGDJ2EhGajQNOH+5GgDXABERkfWZNQNUVFSENWvWIDU1FeXl5Xj00UdRW1uLLVu2cAE0tUn+xSoIAXi6OqGLh3l3FCciIjJXi2eAYmNjERERgR9++AHLli1DQUEB3n77bWvGRjKSW/r7DRAVCm6BJyIi62rxDNDXX3+N5557DrNmzbLIIzCIbsRHYBARUXtq8QzQ3r17UVFRgf79+yM6OhrvvPMOysrKrBkbyUhe2fUF0Fz/Q0RE7aDFBdAdd9yBDz74AIWFhXjqqaewYcMGBAUFQavVIj09HRUVFdaMkxxcLp8CT0RE7cjsXWAeHh6YPn069u7dix9//BF//etf8cYbb8DPzw+jRo2yRowkA7wLNBERtadWb4MHrj2U9M0338S5c+fw8ccfWyomkpkrVRpcqKwDwAKIiIjaR5sKIB2VSoXRo0dj69atlhiOZCbvwrXZH38vF3i4tOrenERERGaxSAFE1Ba6BdDd+QgMIiJqJyyASHL6BdB8BAYREbUTFkAkOd1DULtz/Q8REbUTFkAkuTxugScionbGAogkJYTgFngiImp3LIBIUsXltajWNMBJqUBIZ3epwyEiIplgAUSSyr2+A6xbZ3eoVfx2JCKi9sG/OCQpPgKDiIikwAKIJMX1P0REJAUWQCQpfQHEewAREVE7YgFEkuIMEBERSYEFEElG06BF/sUqAHwMBhERtS8WQCSZ3y5WoUEr4O6sgr+Xi9ThEBGRjLAAIsncuANMoVBIHA0REckJCyCSDNf/EBGRVFgAkWT4EFQiIpIKCyCSTN71u0BzCzwREbU3FkAkmd8vgXEHGBERtS8WQCSJytp6FJfXAuAaICIian8sgEgSutkfnw7O8HZTSxwNERHJDQsgkkQud4AREZGEWACRJPL4FHgiIpKQTRRAy5cvR1hYGFxdXREdHY2srKxG+957771QKBRGHyNHjjTod+LECYwaNQre3t7w8PDAwIEDkZ+fb+1UqIX0O8C4AJqIiCQgeQGUlpaGhIQEJCcnIzs7G5GRkYiJiUFJSYnJ/ps2bUJhYaH+IycnByqVCuPGjdP3OXPmDO6880707NkTmZmZ+OGHH5CUlARXV9f2SouaoVsD1J1b4ImISAJOUgewdOlSzJgxA9OmTQMArFy5Etu2bcOqVaswd+5co/6dO3c2eL1hwwa4u7sbFECvvvoqRowYgTfffFPf1qNHDytlQOYSQvAmiEREJClJC6C6ujocPnwYiYmJ+jalUomhQ4di//79LRojNTUVEyZMgIfHtT+kWq0W27Ztw8svv4yYmBgcOXIE4eHhSExMxOjRo02OUVtbi9raWv3r8vJyAIBGo4FGo2lldpah+/xSx2FJZVdrUVFTD4UCCPRybjQ3R8y9JeSaN8Dcb/xXLuSaN8Dcb/zX0uO2hEIIISz62c1QUFCA4OBg7Nu3D4MGDdK3v/zyy9i9ezcOHjzY5PFZWVmIjo7GwYMHERUVBQAoKipCYGAg3N3d8be//Q333Xcftm/fjnnz5mHXrl245557jMZ57bXXsHDhQqP29evXw93dvY1Z0h+dKQfe+skJXVwEFvRrkDocIiJyEFVVVZg0aRKuXLkCLy+vJvtKfgmsLVJTU9G7d2998QNcmwECgIcffhgvvPACAKBPnz7Yt28fVq5cabIASkxMREJCgv51eXk5QkJCMHz48Ga/gNam0WiQnp6OYcOGQa12jPvlbDx8DvjpOHqF+GDEiP6N9nPE3FtCrnkDzF2Oucs1b4C5WyN33RWclpC0APLx8YFKpUJxcbFBe3FxMQICApo8trKyEhs2bMDrr79uNKaTkxN69epl0H7LLbdg7969JsdycXGBi4uLUbtarbaZb0pbiqWtfr1UAwDo4efZopwcKXdzyDVvgLnLMXe55g0wd0vmbs5Yku4Cc3Z2Rv/+/ZGRkaFv02q1yMjIMLgkZsrGjRtRW1uLxx9/3GjMgQMH4uTJkwbtv/zyC0JDQy0XPLWa7h5A3AFGRERSkfwSWEJCAqZMmYIBAwYgKioKy5YtQ2VlpX5XWFxcHIKDg5GSkmJwXGpqKkaPHo0uXboYjfnSSy9h/PjxuPvuu/VrgL744gtkZma2R0rUDN4FmoiIpCZ5ATR+/HiUlpZiwYIFKCoqQp8+fbB9+3b4+/sDAPLz86FUGk5UnTx5Env37sWOHTtMjvnII49g5cqVSElJwXPPPYeIiAh89tlnuPPOO62eDzWtQSvw6wUWQEREJC3JCyAAiI+PR3x8vMn3TM3aREREoLnNa9OnT8f06dMtER5Z0PlL1dA0CDg7KRHk7SZ1OEREJFOS3wma5CVX9wiMLh5QKhUSR0NERHLFAojaVR7X/xARkQ1gAUTtis8AIyIiW8ACiNpVbilngIiISHosgKhdcQaIiIhsAQsgajc1mgacv1wNAAj36SBxNEREJGcsgKjdnL1+/x9vNzU6ucvztu9ERGQbWABRu8m7Yf2PQsEt8EREJB0WQNRucrn+h4iIbAQLIGo3uh1g3bkDjIiIJMYCiNpNnu4u0FwATUREEmMBRO2Gd4EmIiJbwQKI2sWlyjpcqtIAAMJ83CWOhoiI5I4FELWLvOtb4AO9XeHu7CRxNEREJHcsgKhd6LbAcwcYERHZAhZA1C5y9QugWQAREZH0WABRu/h9ATR3gBERkfRYAFG74D2AiIjIlrAAIqvTaoX+OWC8BEZERLaABRBZXVF5DWo0WqhVCnTt5CZ1OERERCyAyPp063+6dXaHk4rfckREJD3+NSKryy3lIzCIiMi2sAAiq+NT4ImIyNawACKr4zPAiIjI1rAAIqtjAURERLaGBRBZVV29Fr9drALAS2BERGQ7WACRVeVfrIRWAB1cnODbwUXqcIiIiACwACIr090BOtzHAwqFQuJoiIiIrmEBRFbF9T9ERGSLWACRVbEAIiIiW8QCiKyK9wAiIiJbxAKIrEo3A9Sdd4EmIiIbwgKIrKaiRoPSiloAQJiPu8TREBER/Y4FEFmNbvbH19MFnq5qiaMhIiL6HQsgshougCYiIlvFAoisRncPoO4sgIiIyMbYRAG0fPlyhIWFwdXVFdHR0cjKymq077333guFQmH0MXLkSJP9n376aSgUCixbtsxK0VNjOANERES2SvICKC0tDQkJCUhOTkZ2djYiIyMRExODkpISk/03bdqEwsJC/UdOTg5UKhXGjRtn1Hfz5s04cOAAgoKCrJ0GmaDfAebLHWBERGRbJC+Ali5dihkzZmDatGno1asXVq5cCXd3d6xatcpk/86dOyMgIED/kZ6eDnd3d6MC6Pz583j22Wexbt06qNVcgNvehBDILb0KgDNARERke5yk/OR1dXU4fPgwEhMT9W1KpRJDhw7F/v37WzRGamoqJkyYAA+P3//IarVaTJ48GS+99BJuvfXWZseora1FbW2t/nV5eTkAQKPRQKPRtDQdq9B9fqnjMFdJRS0q6xqgVACBnupWxW+vubeVXPMGmPuN/8qFXPMGmPuN/1p63JaQtAAqKytDQ0MD/P39Ddr9/f3x888/N3t8VlYWcnJykJqaatD+97//HU5OTnjuuedaFEdKSgoWLlxo1L5jxw64u9vG/WvS09OlDsEsp68AgBM6Owvs3LG9TWPZW+6WIte8AeYuR3LNG2DullRVVdXivpIWQG2VmpqK3r17IyoqSt92+PBh/Oc//0F2dnaLnz6emJiIhIQE/evy8nKEhIRg+PDh8PLysnjc5tBoNEhPT8ewYcPs6lJe2vfngOPHcWs3X4wY0a9VY9hr7m0l17wB5i7H3OWaN8DcrZG77gpOS0haAPn4+EClUqG4uNigvbi4GAEBAU0eW1lZiQ0bNuD11183aP/uu+9QUlKCbt266dsaGhrw17/+FcuWLcPZs2eNxnJxcYGLi4tRu1qttplvSluKpSXyL9UAALr7dWhz3PaWu6XINW+Aucsxd7nmDTB3S+ZuzliSLoJ2dnZG//79kZGRoW/TarXIyMjAoEGDmjx248aNqK2txeOPP27QPnnyZPzwww84evSo/iMoKAgvvfQSvvnmG6vkQcb09wDiDjAiIrJBkl8CS0hIwJQpUzBgwABERUVh2bJlqKysxLRp0wAAcXFxCA4ORkpKisFxqampGD16NLp06WLQ3qVLF6M2tVqNgIAAREREWDcZ0sstu7YDjDdBJCIiWyR5ATR+/HiUlpZiwYIFKCoqQp8+fbB9+3b9wuj8/HwolYYTVSdPnsTevXuxY8cOKUKmZtQ3aJF/4dpCNG6BJyIiWyR5AQQA8fHxiI+PN/leZmamUVtERASEEC0e39S6H7Kec5eqUa8VcFUrEeDlKnU4RERERiS/ESI5Ht0doMO6eECpbNlOPCIiovbEAogsLvd6AdSDC6CJiMhGsQAii8sr4yMwiIjItrEAIovTbYFnAURERLaKBRBZnG4NULgvCyAiIrJNLIDIoqrq6lF45fpdoDkDRERENooFEFnU2bJr9//p5K5GR3dniaMhIiIyjQUQWZTu8hcfgUFERLaMBRBZVG4pd4AREZHtYwFEFqVfAM0CiIiIbBgLILIo3U0QuQCaiIhsGQsgshghxO+XwLgFnoiIbBgLILKYS1UalNfUQ6G49hwwIiIiW8UCiCxG9wiMIG83uKpVEkdDRETUOBZAZDFnSnVb4Dn7Q0REto0FEFkMd4AREZG9YAFEFpPHh6ASEZGdYAFEFsMZICIishcsgMgitFqBvAu6ewDxMRhERGTbWACRRRRcqUZdvRbOKiWCO7lJHQ4REVGTWACRReReX/8T2sUdKqVC4miIiIiaxgKILILrf4iIyJ6wACKL0BdAvAcQERHZARZAZBF8CCoREdkTFkBkEbrHYIRzBxgREdkBFkDUZrX1DTh3qRoAH4NBRET2gQUQtdmvF6ogBODp6oQuHs5Sh0NERNQsFkDUZrot8N19PKBQcAs8ERHZPhZA1GbcAk9ERPaGBRC1GRdAExGRvWEBRG2mmwHiAmgiIrIXLICozXgJjIiI7A0LIGqTK9UalF2tA8ACiIiI7AcLIGoT3eyPv5cLPFycJI6GiIioZVgAUZv8vgCasz9ERGQ/WABRm+SV6tb/cAcYERHZD5sogJYvX46wsDC4uroiOjoaWVlZjfa99957oVAojD5GjhwJANBoNHjllVfQu3dveHh4ICgoCHFxcSgoKGivdGRF9xDUHtwBRkREdkTyAigtLQ0JCQlITk5GdnY2IiMjERMTg5KSEpP9N23ahMLCQv1HTk4OVCoVxo0bBwCoqqpCdnY2kpKSkJ2djU2bNuHkyZMYNWpUe6YlG7ml3AFGRET2R/JVq0uXLsWMGTMwbdo0AMDKlSuxbds2rFq1CnPnzjXq37lzZ4PXGzZsgLu7u74A8vb2Rnp6ukGfd955B1FRUcjPz0e3bt2slIn8CCG4BZ6IiOySpAVQXV0dDh8+jMTERH2bUqnE0KFDsX///haNkZqaigkTJsDDo/E/wFeuXIFCoUDHjh1Nvl9bW4va2lr96/LycgDXLqdpNJoWxWEtus8vdRymFJXXoFrTAJVSgQBPtcVjtOXcrUmueQPM/cZ/5UKueQPM/cZ/LT1uSyiEEMKin90MBQUFCA4Oxr59+zBo0CB9+8svv4zdu3fj4MGDTR6flZWF6OhoHDx4EFFRUSb71NTUYMiQIejZsyfWrVtnss9rr72GhQsXGrWvX78e7u7uZmQkL6euKPDOcRV8XQXm922QOhwiIpK5qqoqTJo0CVeuXIGXl1eTfSW/BNYWqamp6N27d6PFj0ajwaOPPgohBFasWNHoOImJiUhISNC/Li8vR0hICIYPH97sF9DaNBoN0tPTMWzYMKjVaklj+aOPD/0GHD+BW7v5YsSIfhYf35Zztya55g0wdznmLte8AeZujdx1V3BaQtICyMfHByqVCsXFxQbtxcXFCAgIaPLYyspKbNiwAa+//rrJ93XFz6+//opvv/22yULGxcUFLi4uRu1qtdpmviltKRad/Is1AICb/DytGpst5t4e5Jo3wNzlmLtc8waYuyVzN2csSXeBOTs7o3///sjIyNC3abVaZGRkGFwSM2Xjxo2ora3F448/bvServg5deoUdu7ciS5dulg8dvp9C3w4t8ATEZGdkfwSWEJCAqZMmYIBAwYgKioKy5YtQ2VlpX5XWFxcHIKDg5GSkmJwXGpqKkaPHm1U3Gg0GowdOxbZ2dn48ssv0dDQgKKiIgDXdpA5Ozu3T2IywB1gRERkryQvgMaPH4/S0lIsWLAARUVF6NOnD7Zv3w5/f38AQH5+PpRKw4mqkydPYu/evdixY4fReOfPn8fWrVsBAH369DF4b9euXbj33nutkofcaBq0yL9YBQDozrtAExGRnZG8AAKA+Ph4xMfHm3wvMzPTqC0iIgKNbV4LCwtr9D2ynN8uVqFBK+CmVsHfy3j9FBERkS2T/E7QZJ9uvPylUCgkjoaIiMg8LICoVXQFUHcugCYiIjtkE5fA5KJBK5CVdxElFTXw83RFVHhnqJT2N3vSoBXYd+YCAMBZpUCDVthlHkREJF8sgNrJ9pxCLPziOAqv1OjbAr1dkRzbCw/eFihhZOb5Yx6bjhRgf+5Fu8uDiIjkjZfA2sH2nELMWpttUPwAQNGVGsxam43tOYUSRWYeR8mDiIiIM0BW1qAVWPjFcZjal6ZrW/D5T7gl0MvkZaT6+npcrAXOX66Gk5N0D8xr0Aokff5To3koACz84jiG9Qrg5TAiIrJ5LICsLCvvotGMyR+VVNTinn9kNtHDCQuzv7NoXJYmABReqUFW3kUM6sE7bxMRkW1jAWRlJRVNFz86TkpFozMn2oYGKFUqS4ZltgatQL22+fsrtTRfIiIiKbEAsjI/T9cW9fvvE9EmZ040Gg2++uorjBgRI+nD8vafuYCJHxxotl9L8yUiIpISF0FbWVR4ZwR6u6KxVTEKXNsNFhXeuT3DMpuj5EFERASwALI6lVKB5NheAGBUPOheJ8f2svmFw46SBxEREcACqF08eFsgVjzeDwHehpeHArxdseLxfnZz/xxHyYOIiIhrgNrJg7cFYlivALu/E7Sj5EFERPLGAqgdqZQKh9gi7ih5EBGRfPESGBEREckOCyAiIiKSHRZAREREJDssgIiIiEh2WAARERGR7LAAIiIiItlhAURERESywwKIiIiIZIcFEBEREckO7wRtghACAFBeXi5xJIBGo0FVVRXKy8uhVqulDqddyTV3ueYNMHc55i7XvAHmbo3cdX+3dX/Hm8ICyISKigoAQEhIiMSREBERkbkqKirg7e3dZB+FaEmZJDNarRYFBQXw9PSEQiHtQz7Ly8sREhKC3377DV5eXpLG0t7kmrtc8waYuxxzl2veAHO3Ru5CCFRUVCAoKAhKZdOrfDgDZIJSqUTXrl2lDsOAl5eX7H5AdOSau1zzBpi7HHOXa94Ac7d07s3N/OhwETQRERHJDgsgIiIikh0WQDbOxcUFycnJcHFxkTqUdifX3OWaN8Dc5Zi7XPMGmLvUuXMRNBEREckOZ4CIiIhIdlgAERERkeywACIiIiLZYQFEREREssMCSEIpKSkYOHAgPD094efnh9GjR+PkyZNNHrNmzRooFAqDD1dX13aK2HJee+01ozx69uzZ5DEbN25Ez5494erqit69e+Orr75qp2gtKywszCh3hUKB2bNnm+xvr+d8z549iI2NRVBQEBQKBbZs2WLwvhACCxYsQGBgINzc3DB06FCcOnWq2XGXL1+OsLAwuLq6Ijo6GllZWVbKoPWayl2j0eCVV15B79694eHhgaCgIMTFxaGgoKDJMVvzMyOF5s771KlTjfJ48MEHmx3X1s97c3mb+plXKBT4xz/+0eiY9nDOW/J3rKamBrNnz0aXLl3QoUMHjBkzBsXFxU2O29rfD+ZgASSh3bt3Y/bs2Thw4ADS09Oh0WgwfPhwVFZWNnmcl5cXCgsL9R+//vprO0VsWbfeeqtBHnv37m207759+zBx4kQ88cQTOHLkCEaPHo3Ro0cjJyenHSO2jEOHDhnknZ6eDgAYN25co8fY4zmvrKxEZGQkli9fbvL9N998E2+99RZWrlyJgwcPwsPDAzExMaipqWl0zLS0NCQkJCA5ORnZ2dmIjIxETEwMSkpKrJVGqzSVe1VVFbKzs5GUlITs7Gxs2rQJJ0+exKhRo5od15yfGak0d94B4MEHHzTI4+OPP25yTHs4783lfWO+hYWFWLVqFRQKBcaMGdPkuLZ+zlvyd+yFF17AF198gY0bN2L37t0oKCjAX/7ylybHbc3vB7MJshklJSUCgNi9e3ejfVavXi28vb3bLygrSU5OFpGRkS3u/+ijj4qRI0catEVHR4unnnrKwpG1vzlz5ogePXoIrVZr8n1HOOcAxObNm/WvtVqtCAgIEP/4xz/0bZcvXxYuLi7i448/bnScqKgoMXv2bP3rhoYGERQUJFJSUqwStyX8MXdTsrKyBADx66+/NtrH3J8ZW2Aq9ylTpoiHH37YrHHs7by35Jw//PDD4v7772+yjz2e8z/+Hbt8+bJQq9Vi48aN+j4nTpwQAMT+/ftNjtHa3w/m4gyQDbly5QoAoHPnzk32u3r1KkJDQxESEoKHH34YP/30U3uEZ3GnTp1CUFAQunfvjsceewz5+fmN9t2/fz+GDh1q0BYTE4P9+/dbO0yrqqurw9q1azF9+vQmH7zrKOdcJy8vD0VFRQbn1NvbG9HR0Y2e07q6Ohw+fNjgGKVSiaFDh9r998GVK1egUCjQsWPHJvuZ8zNjyzIzM+Hn54eIiAjMmjULFy5caLSvI5734uJibNu2DU888USzfe3tnP/x79jhw4eh0WgMzl/Pnj3RrVu3Rs9fa34/tAYLIBuh1Wrx/PPPY8iQIbjtttsa7RcREYFVq1bh888/x9q1a6HVajF48GCcO3euHaNtu+joaKxZswbbt2/HihUrkJeXh7vuugsVFRUm+xcVFcHf39+gzd/fH0VFRe0RrtVs2bIFly9fxtSpUxvt4yjn/Ea682bOOS0rK0NDQ4PDfR/U1NTglVdewcSJE5t8KKS5PzO26sEHH8RHH32EjIwM/P3vf8fu3bvx0EMPoaGhwWR/RzzvH374ITw9PZu9DGRv59zU37GioiI4OzsbFfdNnb/W/H5oDT4N3kbMnj0bOTk5zV7fHTRoEAYNGqR/PXjwYNxyyy147733sGjRImuHaTEPPfSQ/r9vv/12REdHIzQ0FJ988kmL/q/IUaSmpuKhhx5CUFBQo30c5ZyTMY1Gg0cffRRCCKxYsaLJvo7yMzNhwgT9f/fu3Ru33347evTogczMTDzwwAMSRtZ+Vq1ahccee6zZzQz2ds5b+nfMVnAGyAbEx8fjyy+/xK5du9C1a1ezjlWr1ejbty9Onz5tpejaR8eOHfGnP/2p0TwCAgKMdg0UFxcjICCgPcKzil9//RU7d+7Ek08+adZxjnDOdefNnHPq4+MDlUrlMN8HuuLn119/RXp6epOzP6Y09zNjL7p37w4fH59G83C08/7dd9/h5MmTZv/cA7Z9zhv7OxYQEIC6ujpcvnzZoH9T5681vx9agwWQhIQQiI+Px+bNm/Htt98iPDzc7DEaGhrw448/IjAw0AoRtp+rV6/izJkzjeYxaNAgZGRkGLSlp6cbzIzYm9WrV8PPzw8jR4406zhHOOfh4eEICAgwOKfl5eU4ePBgo+fU2dkZ/fv3NzhGq9UiIyPD7r4PdMXPqVOnsHPnTnTp0sXsMZr7mbEX586dw4ULFxrNw5HOO3Bt1rd///6IjIw0+1hbPOfN/R3r378/1Gq1wfk7efIk8vPzGz1/rfn90NrgSSKzZs0S3t7eIjMzUxQWFuo/qqqq9H0mT54s5s6dq3+9cOFC8c0334gzZ86Iw4cPiwkTJghXV1fx008/SZFCq/31r38VmZmZIi8vT/zvf/8TQ4cOFT4+PqKkpEQIYZz3//73P+Hk5CT++c9/ihMnTojk5GShVqvFjz/+KFUKbdLQ0CC6desmXnnlFaP3HOWcV1RUiCNHjogjR44IAGLp0qXiyJEj+p1Ob7zxhujYsaP4/PPPxQ8//CAefvhhER4eLqqrq/Vj3H///eLtt9/Wv96wYYNwcXERa9asEcePHxczZ84UHTt2FEVFRe2eX1Oayr2urk6MGjVKdO3aVRw9etTgZ7+2tlY/xh9zb+5nxlY0lXtFRYV48cUXxf79+0VeXp7YuXOn6Nevn7j55ptFTU2Nfgx7PO/Nfb8LIcSVK1eEu7u7WLFihckx7PGct+Tv2NNPPy26desmvv32W/H999+LQYMGiUGDBhmMExERITZt2qR/3ZLfD23FAkhCAEx+rF69Wt/nnnvuEVOmTNG/fv7550W3bt2Es7Oz8Pf3FyNGjBDZ2dntH3wbjR8/XgQGBgpnZ2cRHBwsxo8fL06fPq1//495CyHEJ598Iv70pz8JZ2dnceutt4pt27a1c9SW88033wgA4uTJk0bvOco537Vrl8nvb11uWq1WJCUlCX9/f+Hi4iIeeOABo69HaGioSE5ONmh7++239V+PqKgoceDAgXbKqOWayj0vL6/Rn/1du3bpx/hj7s39zNiKpnKvqqoSw4cPF76+vkKtVovQ0FAxY8YMo0LGHs97c9/vQgjx3nvvCTc3N3H58mWTY9jjOW/J37Hq6mrxzDPPiE6dOgl3d3fxyCOPiMLCQqNxbjymJb8f2kpx/RMTERERyQbXABEREZHssAAiIiIi2WEBRERERLLDAoiIiIhkhwUQERERyQ4LICIiIpIdFkBEREQkOyyAiIiISHZYABGRXSktLcWsWbPQrVs3uLi4ICAgADExMfjf//4HAFAoFNiyZYu0QRKRzXOSOgAiInOMGTMGdXV1+PDDD9G9e3cUFxcjIyMDFy5ckDo0IrIjnAEiIrtx+fJlfPfdd/j73/+O++67D6GhoYiKikJiYiJGjRqFsLAwAMAjjzwChUKhfw0An3/+Ofr16wdXV1d0794dCxcuRH19vf59hUKBFStW4KGHHoKbmxu6d++OTz/9VP9+XV0d4uPjERgYCFdXV4SGhiIlJaW9UiciC2MBRER2o0OHDujQoQO2bNmC2tpao/cPHToEAFi9ejUKCwv1r7/77jvExcVhzpw5OH78ON577z2sWbMGixcvNjg+KSkJY8aMwbFjx/DYY49hwoQJOHHiBADgrbfewtatW/HJJ5/g5MmTWLdunUGBRUT2hQ9DJSK78tlnn2HGjBmorq5Gv379cM8992DChAm4/fbbAVybydm8eTNGjx6tP2bo0KF44IEHkJiYqG9bu3YtXn75ZRQUFOiPe/rpp7FixQp9nzvuuAP9+vXDu+++i+eeew4//fQTdu7cCYVC0T7JEpHVcAaIiOzKmDFjUFBQgK1bt+LBBx9EZmYm+vXrhzVr1jR6zLFjx/D666/rZ5A6dOiAGTNmoLCwEFVVVfp+gwYNMjhu0KBB+hmgqVOn4ujRo4iIiMBzzz2HHTt2WCU/ImofLICIyO64urpi2LBhSEpKwr59+zB16lQkJyc32v/q1atYuHAhjh49qv/48ccfcerUKbi6urboc/br1w95eXlYtGgRqqur8eijj2Ls2LGWSomI2hkLICKye7169UJlZSUAQK1Wo6GhweD9fv364eTJk7jpppuMPpTK338NHjhwwOC4AwcO4JZbbtG/9vLywvjx4/HBBx8gLS0Nn332GS5evGjFzIjIWrgNnojsxoULFzBu3DhMnz4dt99+Ozw9PfH999/jzTffxMMPPwwACAsLQ0ZGBoYMGQIXFxd06tQJCxYswJ///Gd069YNY8eOhVKpxLFjx5CTk4O//e1v+vE3btyIAQMG4M4778S6deuQlZWF1NRUAMDSpUsRGBiIvn37QqlUYuPGjQgICEDHjh2l+FIQUVsJIiI7UVNTI+bOnSv69esnvL29hbu7u4iIiBDz588XVVVVQgghtm7dKm666Sbh5OQkQkND9cdu375dDB48WLi5uQkvLy8RFRUl3n//ff37AMTy5cvFsGHDhIuLiwgLCxNpaWn6999//33Rp08f4eHhIby8vMQDDzwgsrOz2y13IrIs7gIjIoLp3WNE5Li4BoiIiIhkhwUQERERyQ4XQRMRAeBqACJ54QwQERERyQ4LICIiIpIdFkBEREQkOyyAiIiISHZYABEREZHssAAiIiIi2WEBRERERLLDAoiIiIhkhwUQERERyc7/A5Pa/V0oetonAAAAAElFTkSuQmCC\n"
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 12,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "67Gx9rtA3Qcg",
        "outputId": "aa7dbd9f-d641-45ac-ddde-744804b71985"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Probabilities: No fever=0.550872802734375, Fever=0.4491272568702698\n",
            "This patient has : No fever\n",
            "Recommended Medication for patient to take: Rest and hydration\n"
          ]
        }
      ],
      "source": [
        "#pretrained model to use it make predictions on new data\n",
        "from transformers import BertTokenizer, BertForSequenceClassification\n",
        "import torch\n",
        "\n",
        "# Load the trained model and tokenizer\n",
        "model = BertForSequenceClassification.from_pretrained(\"fever_detection_model\")\n",
        "tokenizer = BertTokenizer.from_pretrained(\"fever_detection_tokenizer\")\n",
        "\n",
        "# Prediction function\n",
        "def predict(text):\n",
        "    inputs = tokenizer(text, return_tensors=\"pt\", truncation=True, max_length=128, padding=\"max_length\")\n",
        "    outputs = model(**inputs)\n",
        "    logits = outputs.logits\n",
        "    probabilities = torch.nn.functional.softmax(logits, dim=1).squeeze()\n",
        "\n",
        "    predicted_label = torch.argmax(probabilities).item()\n",
        "    probability_no_fever = probabilities[0].item()\n",
        "    probability_fever = probabilities[1].item()\n",
        "\n",
        "    print(f\"Probabilities: No fever={probability_no_fever}, Fever={probability_fever}\")\n",
        "\n",
        "    diagnosis = \"Fever detected\" if predicted_label == 1 else \"No fever\"\n",
        "\n",
        "    # Medication mapping\n",
        "    medication = {\n",
        "        \"Fever detected\": \"Paracetamol\",\n",
        "        \"No fever\": \"Rest and hydration\"\n",
        "    }\n",
        "\n",
        "    return diagnosis, medication[diagnosis]\n",
        "\n",
        "# Test the inference\n",
        "text = \"The patient feels tired but has no fever.\"\n",
        "diagnosis, recommended_medication = predict(text)\n",
        "print(f\"This patient has : {diagnosis}\")\n",
        "print(f\"Recommended Medication for patient to take: {recommended_medication}\")"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPu5DnjDBJr7rhP1PXHRyhQ",
      "include_colab_link" : True

    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    },
    "widgets": {
      "application/vnd.jupyter.widget-state+json": {
        "c7251ae2e9cb44979702edf0e15112cf": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HBoxModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HBoxModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HBoxView",
            "box_style": "",
            "children": [
              "IPY_MODEL_e07740fa1e4d4e4581f9e13c9f051c4c",
              "IPY_MODEL_bd9045a968574336b795c6ea495741d6",
              "IPY_MODEL_49fac4811f5e48af9bbf43ec2d204b13"
            ],
            "layout": "IPY_MODEL_e506614ef2564fa69b4647d8611904b3"
          }
        },
        "e07740fa1e4d4e4581f9e13c9f051c4c": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HTMLModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HTMLModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HTMLView",
            "description": "",
            "description_tooltip": None,
            "layout": "IPY_MODEL_82ff1d1f590143c1b9b075e182052072",
            "placeholder": "​",
            "style": "IPY_MODEL_0a4ca7cc390c4552abfa9e779e10897f",
            "value": "Map: 100%"
          }
        },
        "bd9045a968574336b795c6ea495741d6": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "FloatProgressModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "FloatProgressModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ProgressView",
            "bar_style": "success",
            "description": "",
            "description_tooltip": None,
            "layout": "IPY_MODEL_cad39de900bd4354a3c38a478243bc7d",
            "max": 27,
            "min": 0,
            "orientation": "horizontal",
            "style": "IPY_MODEL_c5e71e82dff64fd5b95c1c4511293aa5",
            "value": 27
          }
        },
        "49fac4811f5e48af9bbf43ec2d204b13": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HTMLModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HTMLModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HTMLView",
            "description": "",
            "description_tooltip": None,
            "layout": "IPY_MODEL_aec89e645a8a419688cc38775a8633ca",
            "placeholder": "​",
            "style": "IPY_MODEL_ab8854f49eb1448f96e99d737b71a0f0",
            "value": " 27/27 [00:00&lt;00:00, 217.50 examples/s]"
          }
        },
        "e506614ef2564fa69b4647d8611904b3": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": None,
            "align_items": None,
            "align_self": None,
            "border": None,
            "bottom": None,
            "display": None,
            "flex": None,
            "flex_flow": None,
            "grid_area":None,
            "grid_auto_columns": None,
            "grid_auto_flow": None,
            "grid_auto_rows": None,
            "grid_column": None,
            "grid_gap":None,
            "grid_row": None,
            "grid_template_areas": None,
            "grid_template_columns": None,
            "grid_template_rows":None,
            "height": None,
            "justify_content": None,
            "justify_items": None,
            "left": None,
            "margin": None,
            "max_height":None,
            "max_width": None,
            "min_height": None,
            "min_width": None,
            "object_fit": None,
            "object_position":None,
            "order": None,
            "overflow": None,
            "overflow_x": None,
            "overflow_y":None,
            "padding": None,
            "right": None,
            "top": None,
            "visibility":None,
            "width":None
          }
        },
        "82ff1d1f590143c1b9b075e182052072": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content":None,
            "align_items": None,
            "align_self": None,
            "border":None,
            "bottom": None,
            "display": None,
            "flex":None,
            "flex_flow":None,
            "grid_area":None,
            "grid_auto_columns":None,
            "grid_auto_flow":None,
            "grid_auto_rows": None,
            "grid_column":None,
            "grid_gap":None,
            "grid_row":None,
            "grid_template_areas":None,
            "grid_template_columns":None,
            "grid_template_rows":None,
            "height":None,
            "justify_content":None,
            "justify_items":None,
            "left":None,
            "margin": None,
            "max_height":None,
            "max_width":None,
            "min_height":None,
            "min_width":None,
            "object_fit": None,
            "object_position": None,
            "order": None,
            "overflow":None,
            "overflow_x":None,
            "overflow_y":None,
            "padding": None,
            "right":None,
            "top":None,
            "visibility": None,
            "width":None
          }
        },
        "0a4ca7cc390c4552abfa9e779e10897f": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "cad39de900bd4354a3c38a478243bc7d": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": None,
            "align_items":None,
            "align_self": None,
            "border":None,
            "bottom": None,
            "display":None,
            "flex": None,
            "flex_flow":None,
            "grid_area":None,
            "grid_auto_columns":None,
            "grid_auto_flow":None,
            "grid_auto_rows":None,
            "grid_column":None,
            "grid_gap":None,
            "grid_row":None,
            "grid_template_areas": None,
            "grid_template_columns": None,
            "grid_template_rows": None,
            "height": None,
            "justify_content":None,
            "justify_items": None,
            "left":None,
            "margin":None,
            "max_height": None,
            "max_width": None,
            "min_height":None,
            "min_width":None,
            "object_fit":None,
            "object_position": None,
            "order": None,
            "overflow":None,
            "overflow_x":None,
            "overflow_y":None,
            "padding":None,
            "right":None,
            "top":None,
            "visibility":None,
            "width":None
          }
        },
        "c5e71e82dff64fd5b95c1c4511293aa5": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ProgressStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ProgressStyleModel",
            "_view_count":None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "bar_color":None,
            "description_width": ""
          }
        },
        "aec89e645a8a419688cc38775a8633ca": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content":None,
            "align_items": None,
            "align_self":None,
            "border":None,
            "bottom": None,
            "display":None,
            "flex":None,
            "flex_flow":None,
            "grid_area":None,
            "grid_auto_columns":None,
            "grid_auto_flow":None,
            "grid_auto_rows":None,
            "grid_column":None,
            "grid_gap":None,
            "grid_row": None,
            "grid_template_areas":None,
            "grid_template_columns":None,
            "grid_template_rows":None,
            "height":None,
            "justify_content":None,
            "justify_items":None,
            "left": None,
            "margin": None,
            "max_height":None,
            "max_width": None,
            "min_height": None,
            "min_width":None,
            "object_fit":None,
            "object_position": None,
            "order": None,
            "overflow":None,
            "overflow_x":None,
            "overflow_y":None,
            "padding":None,
            "right":None,
            "top":None,
            "visibility":None,
            "width": None
          }
        },
        "ab8854f49eb1448f96e99d737b71a0f0": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "5202c29a607c44ebb64f797624f6ebe2": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HBoxModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HBoxModel",
            "_view_count":None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HBoxView",
            "box_style": "",
            "children": [
              "IPY_MODEL_c70de9546de04c10825c137eeb69b8b3",
              "IPY_MODEL_7f0c7448110949659a2ca91e87690fd9",
              "IPY_MODEL_5ec567ca313b4205af5184e60df435fb"
            ],
            "layout": "IPY_MODEL_421b0adc20cc4330afb79c8c829b0bac"
          }
        },
        "c70de9546de04c10825c137eeb69b8b3": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HTMLModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HTMLModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HTMLView",
            "description": "",
            "description_tooltip": None,
            "layout": "IPY_MODEL_4568c7376aba4329b01368812c02441b",
            "placeholder": "​",
            "style": "IPY_MODEL_7ae671b9ce9a4c1d85a6314965dc169a",
            "value": "Map: 100%"
          }
        },
        "7f0c7448110949659a2ca91e87690fd9": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "FloatProgressModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "FloatProgressModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "ProgressView",
            "bar_style": "success",
            "description": "",
            "description_tooltip": None,
            "layout": "IPY_MODEL_bad42d8072844c4e936afffa72d19b5d",
            "max": 7,
            "min": 0,
            "orientation": "horizontal",
            "style": "IPY_MODEL_9de191c3d6014f9e85b5bc3b7a51b0cd",
            "value": 7
          }
        },
        "5ec567ca313b4205af5184e60df435fb": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "HTMLModel",
          "model_module_version": "1.5.0",
          "state": {
            "_dom_classes": [],
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "HTMLModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/controls",
            "_view_module_version": "1.5.0",
            "_view_name": "HTMLView",
            "description": "",
            "description_tooltip": None,
            "layout": "IPY_MODEL_725432b69f5a45cfa25b6fd115aa7567",
            "placeholder": "​",
            "style": "IPY_MODEL_4988a34b3f24414b945da5fce490b041",
            "value": " 7/7 [00:00&lt;00:00, 63.49 examples/s]"
          }
        },
        "421b0adc20cc4330afb79c8c829b0bac": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content":None,
            "align_items":None,
            "align_self":None,
            "border":None,
            "bottom": None,
            "display": None,
            "flex":None,
            "flex_flow": None,
            "grid_area":None,
            "grid_auto_columns": None,
            "grid_auto_flow": None,
            "grid_auto_rows":None,
            "grid_column":None,
            "grid_gap":None,
            "grid_row": None,
            "grid_template_areas": None,
            "grid_template_columns":None,
            "grid_template_rows": None,
            "height": None,
            "justify_content": None,
            "justify_items": None,
            "left": None,
            "margin": None,
            "max_height":None,
            "max_width": None,
            "min_height": None,
            "min_width": None,
            "object_fit": None,
            "object_position": None,
            "order": None,
            "overflow": None,
            "overflow_x": None,
            "overflow_y": None,
            "padding": None,
            "right": None,
            "top":None,
            "visibility": None,
            "width": None
          }
        },
        "4568c7376aba4329b01368812c02441b": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count":None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": None,
            "align_items":None,
            "align_self":None,
            "border":None,
            "bottom": None,
            "display": None,
            "flex": None,
            "flex_flow": None,
            "grid_area":None,
            "grid_auto_columns":None,
            "grid_auto_flow": None,
            "grid_auto_rows": None,
            "grid_column": None,
            "grid_gap":None,
            "grid_row": None,
            "grid_template_areas": None,
            "grid_template_columns": None,
            "grid_template_rows": None,
            "height":None,
            "justify_content":None,
            "justify_items": None,
            "left": None,
            "margin": None,
            "max_height":None,
            "max_width": None,
            "min_height": None,
            "min_width":None,
            "object_fit":None,
            "object_position":None,
            "order":None,
            "overflow": None,
            "overflow_x":None,
            "overflow_y":None,
            "padding": None,
            "right": None,
            "top":None,
            "visibility":None,
            "width":None
          }
        },
        "7ae671b9ce9a4c1d85a6314965dc169a": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        },
        "bad42d8072844c4e936afffa72d19b5d": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content":None,
            "align_items": None,
            "align_self": None,
            "border": None,
            "bottom": None,
            "display": None,
            "flex": None,
            "flex_flow":None,
            "grid_area": None,
            "grid_auto_columns": None,
            "grid_auto_flow":None,
            "grid_auto_rows": None,
            "grid_column": None,
            "grid_gap":None,
            "grid_row": None,
            "grid_template_areas":None,
            "grid_template_columns": None,
            "grid_template_rows":None,
            "height":None,
            "justify_content": None,
            "justify_items": None,
            "left": None,
            "margin": None,
            "max_height":None,
            "max_width":None,
            "min_height": None,
            "min_width": None,
            "object_fit": None,
            "object_position": None,
            "order":None,
            "overflow": None,
            "overflow_x": None,
            "overflow_y":None,
            "padding": None,
            "right": None,
            "top": None,
            "visibility": None,
            "width": None
          }
        },
        "9de191c3d6014f9e85b5bc3b7a51b0cd": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "ProgressStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "ProgressStyleModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "bar_color": None,
            "description_width": ""
          }
        },
        "725432b69f5a45cfa25b6fd115aa7567": {
          "model_module": "@jupyter-widgets/base",
          "model_name": "LayoutModel",
          "model_module_version": "1.2.0",
          "state": {
            "_model_module": "@jupyter-widgets/base",
            "_model_module_version": "1.2.0",
            "_model_name": "LayoutModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "LayoutView",
            "align_content": None,
            "align_items": None,
            "align_self":None,
            "border": None,
            "bottom": None,
            "display": None,
            "flex": None,
            "flex_flow": None,
            "grid_area": None,
            "grid_auto_columns": None,
            "grid_auto_flow":None,
            "grid_auto_rows": None,
            "grid_column": None,
            "grid_gap": None,
            "grid_row": None,
            "grid_template_areas": None,
            "grid_template_columns": v,
            "grid_template_rows":None,
            "height": None,
            "justify_content":None,
            "justify_items":None,
            "left": None,
            "margin": None,
            "max_height": None,
            "max_width": None,
            "min_height": None,
            "min_width": None,
            "object_fit": None,
            "object_position": v,
            "order": None,
            "overflow": None,
            "overflow_x":None,
            "overflow_y": None,
            "padding": None,
            "right":None,
            "top": None,
            "visibility": None,
            "width": None
          }
        },
        "4988a34b3f24414b945da5fce490b041": {
          "model_module": "@jupyter-widgets/controls",
          "model_name": "DescriptionStyleModel",
          "model_module_version": "1.5.0",
          "state": {
            "_model_module": "@jupyter-widgets/controls",
            "_model_module_version": "1.5.0",
            "_model_name": "DescriptionStyleModel",
            "_view_count": None,
            "_view_module": "@jupyter-widgets/base",
            "_view_module_version": "1.2.0",
            "_view_name": "StyleView",
            "description_width": ""
          }
        }
      }
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
